// Code generated by go-swagger; DO NOT EDIT.

package nodes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewNodesListParams creates a new NodesListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewNodesListParams() *NodesListParams {
	return &NodesListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewNodesListParamsWithTimeout creates a new NodesListParams object
// with the ability to set a timeout on a request.
func NewNodesListParamsWithTimeout(timeout time.Duration) *NodesListParams {
	return &NodesListParams{
		timeout: timeout,
	}
}

// NewNodesListParamsWithContext creates a new NodesListParams object
// with the ability to set a context for a request.
func NewNodesListParamsWithContext(ctx context.Context) *NodesListParams {
	return &NodesListParams{
		Context: ctx,
	}
}

// NewNodesListParamsWithHTTPClient creates a new NodesListParams object
// with the ability to set a custom HTTPClient for a request.
func NewNodesListParamsWithHTTPClient(client *http.Client) *NodesListParams {
	return &NodesListParams{
		HTTPClient: client,
	}
}

/* NodesListParams contains all the parameters to send to the API endpoint
   for the nodes list operation.

   Typically these are written to a http.Request.
*/
type NodesListParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the nodes list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *NodesListParams) WithDefaults() *NodesListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the nodes list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *NodesListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the nodes list params
func (o *NodesListParams) WithTimeout(timeout time.Duration) *NodesListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the nodes list params
func (o *NodesListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the nodes list params
func (o *NodesListParams) WithContext(ctx context.Context) *NodesListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the nodes list params
func (o *NodesListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the nodes list params
func (o *NodesListParams) WithHTTPClient(client *http.Client) *NodesListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the nodes list params
func (o *NodesListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *NodesListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
