// Code generated by go-swagger; DO NOT EDIT.

package volumes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewVolumeRecoverInitiateParams creates a new VolumeRecoverInitiateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewVolumeRecoverInitiateParams() *VolumeRecoverInitiateParams {
	return &VolumeRecoverInitiateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewVolumeRecoverInitiateParamsWithTimeout creates a new VolumeRecoverInitiateParams object
// with the ability to set a timeout on a request.
func NewVolumeRecoverInitiateParamsWithTimeout(timeout time.Duration) *VolumeRecoverInitiateParams {
	return &VolumeRecoverInitiateParams{
		timeout: timeout,
	}
}

// NewVolumeRecoverInitiateParamsWithContext creates a new VolumeRecoverInitiateParams object
// with the ability to set a context for a request.
func NewVolumeRecoverInitiateParamsWithContext(ctx context.Context) *VolumeRecoverInitiateParams {
	return &VolumeRecoverInitiateParams{
		Context: ctx,
	}
}

// NewVolumeRecoverInitiateParamsWithHTTPClient creates a new VolumeRecoverInitiateParams object
// with the ability to set a custom HTTPClient for a request.
func NewVolumeRecoverInitiateParamsWithHTTPClient(client *http.Client) *VolumeRecoverInitiateParams {
	return &VolumeRecoverInitiateParams{
		HTTPClient: client,
	}
}

/*
VolumeRecoverInitiateParams contains all the parameters to send to the API endpoint

	for the volume recover initiate operation.

	Typically these are written to a http.Request.
*/
type VolumeRecoverInitiateParams struct {

	// Authorization.
	Authorization *string

	// Volume.
	Volume string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the volume recover initiate params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VolumeRecoverInitiateParams) WithDefaults() *VolumeRecoverInitiateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the volume recover initiate params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VolumeRecoverInitiateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the volume recover initiate params
func (o *VolumeRecoverInitiateParams) WithTimeout(timeout time.Duration) *VolumeRecoverInitiateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the volume recover initiate params
func (o *VolumeRecoverInitiateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the volume recover initiate params
func (o *VolumeRecoverInitiateParams) WithContext(ctx context.Context) *VolumeRecoverInitiateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the volume recover initiate params
func (o *VolumeRecoverInitiateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the volume recover initiate params
func (o *VolumeRecoverInitiateParams) WithHTTPClient(client *http.Client) *VolumeRecoverInitiateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the volume recover initiate params
func (o *VolumeRecoverInitiateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the volume recover initiate params
func (o *VolumeRecoverInitiateParams) WithAuthorization(authorization *string) *VolumeRecoverInitiateParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the volume recover initiate params
func (o *VolumeRecoverInitiateParams) SetAuthorization(authorization *string) {
	o.Authorization = authorization
}

// WithVolume adds the volume to the volume recover initiate params
func (o *VolumeRecoverInitiateParams) WithVolume(volume string) *VolumeRecoverInitiateParams {
	o.SetVolume(volume)
	return o
}

// SetVolume adds the volume to the volume recover initiate params
func (o *VolumeRecoverInitiateParams) SetVolume(volume string) {
	o.Volume = volume
}

// WriteToRequest writes these params to a swagger request
func (o *VolumeRecoverInitiateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Authorization != nil {

		// header param authorization
		if err := r.SetHeaderParam("authorization", *o.Authorization); err != nil {
			return err
		}
	}

	// path param volume
	if err := r.SetPathParam("volume", o.Volume); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
