/*
Volumez API

Volumez orchestrator API

API version: 1.0.0 - 9cdeb26f
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the PutAzureSSOMappingRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PutAzureSSOMappingRequest{}

// PutAzureSSOMappingRequest struct for PutAzureSSOMappingRequest
type PutAzureSSOMappingRequest struct {
	SecurityGroupID string `json:"SecurityGroupID"`
}

type _PutAzureSSOMappingRequest PutAzureSSOMappingRequest

// NewPutAzureSSOMappingRequest instantiates a new PutAzureSSOMappingRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPutAzureSSOMappingRequest(securityGroupID string) *PutAzureSSOMappingRequest {
	this := PutAzureSSOMappingRequest{}
	this.SecurityGroupID = securityGroupID
	return &this
}

// NewPutAzureSSOMappingRequestWithDefaults instantiates a new PutAzureSSOMappingRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPutAzureSSOMappingRequestWithDefaults() *PutAzureSSOMappingRequest {
	this := PutAzureSSOMappingRequest{}
	return &this
}

// GetSecurityGroupID returns the SecurityGroupID field value
func (o *PutAzureSSOMappingRequest) GetSecurityGroupID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SecurityGroupID
}

// GetSecurityGroupIDOk returns a tuple with the SecurityGroupID field value
// and a boolean to check if the value has been set.
func (o *PutAzureSSOMappingRequest) GetSecurityGroupIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SecurityGroupID, true
}

// SetSecurityGroupID sets field value
func (o *PutAzureSSOMappingRequest) SetSecurityGroupID(v string) {
	o.SecurityGroupID = v
}

func (o PutAzureSSOMappingRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PutAzureSSOMappingRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["SecurityGroupID"] = o.SecurityGroupID
	return toSerialize, nil
}

func (o *PutAzureSSOMappingRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"SecurityGroupID",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPutAzureSSOMappingRequest := _PutAzureSSOMappingRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPutAzureSSOMappingRequest)

	if err != nil {
		return err
	}

	*o = PutAzureSSOMappingRequest(varPutAzureSSOMappingRequest)

	return err
}

type NullablePutAzureSSOMappingRequest struct {
	value *PutAzureSSOMappingRequest
	isSet bool
}

func (v NullablePutAzureSSOMappingRequest) Get() *PutAzureSSOMappingRequest {
	return v.value
}

func (v *NullablePutAzureSSOMappingRequest) Set(val *PutAzureSSOMappingRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePutAzureSSOMappingRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePutAzureSSOMappingRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePutAzureSSOMappingRequest(val *PutAzureSSOMappingRequest) *NullablePutAzureSSOMappingRequest {
	return &NullablePutAzureSSOMappingRequest{value: val, isSet: true}
}

func (v NullablePutAzureSSOMappingRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePutAzureSSOMappingRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
