/*
Volumez API

Volumez orchestrator API

API version: 1.0.0 - 8d1ee8c4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GetTenantHostResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetTenantHostResponse{}

// GetTenantHostResponse struct for GetTenantHostResponse
type GetTenantHostResponse struct {
	StatusCode int32   `json:"StatusCode"`
	Message    *string `json:"Message,omitempty"`
	TenantHost *string `json:"TenantHost,omitempty"`
	TenantID   *string `json:"TenantID,omitempty"`
}

type _GetTenantHostResponse GetTenantHostResponse

// NewGetTenantHostResponse instantiates a new GetTenantHostResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetTenantHostResponse(statusCode int32) *GetTenantHostResponse {
	this := GetTenantHostResponse{}
	this.StatusCode = statusCode
	return &this
}

// NewGetTenantHostResponseWithDefaults instantiates a new GetTenantHostResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetTenantHostResponseWithDefaults() *GetTenantHostResponse {
	this := GetTenantHostResponse{}
	return &this
}

// GetStatusCode returns the StatusCode field value
func (o *GetTenantHostResponse) GetStatusCode() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.StatusCode
}

// GetStatusCodeOk returns a tuple with the StatusCode field value
// and a boolean to check if the value has been set.
func (o *GetTenantHostResponse) GetStatusCodeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StatusCode, true
}

// SetStatusCode sets field value
func (o *GetTenantHostResponse) SetStatusCode(v int32) {
	o.StatusCode = v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *GetTenantHostResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTenantHostResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *GetTenantHostResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *GetTenantHostResponse) SetMessage(v string) {
	o.Message = &v
}

// GetTenantHost returns the TenantHost field value if set, zero value otherwise.
func (o *GetTenantHostResponse) GetTenantHost() string {
	if o == nil || IsNil(o.TenantHost) {
		var ret string
		return ret
	}
	return *o.TenantHost
}

// GetTenantHostOk returns a tuple with the TenantHost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTenantHostResponse) GetTenantHostOk() (*string, bool) {
	if o == nil || IsNil(o.TenantHost) {
		return nil, false
	}
	return o.TenantHost, true
}

// HasTenantHost returns a boolean if a field has been set.
func (o *GetTenantHostResponse) HasTenantHost() bool {
	if o != nil && !IsNil(o.TenantHost) {
		return true
	}

	return false
}

// SetTenantHost gets a reference to the given string and assigns it to the TenantHost field.
func (o *GetTenantHostResponse) SetTenantHost(v string) {
	o.TenantHost = &v
}

// GetTenantID returns the TenantID field value if set, zero value otherwise.
func (o *GetTenantHostResponse) GetTenantID() string {
	if o == nil || IsNil(o.TenantID) {
		var ret string
		return ret
	}
	return *o.TenantID
}

// GetTenantIDOk returns a tuple with the TenantID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTenantHostResponse) GetTenantIDOk() (*string, bool) {
	if o == nil || IsNil(o.TenantID) {
		return nil, false
	}
	return o.TenantID, true
}

// HasTenantID returns a boolean if a field has been set.
func (o *GetTenantHostResponse) HasTenantID() bool {
	if o != nil && !IsNil(o.TenantID) {
		return true
	}

	return false
}

// SetTenantID gets a reference to the given string and assigns it to the TenantID field.
func (o *GetTenantHostResponse) SetTenantID(v string) {
	o.TenantID = &v
}

func (o GetTenantHostResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetTenantHostResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["StatusCode"] = o.StatusCode
	if !IsNil(o.Message) {
		toSerialize["Message"] = o.Message
	}
	if !IsNil(o.TenantHost) {
		toSerialize["TenantHost"] = o.TenantHost
	}
	if !IsNil(o.TenantID) {
		toSerialize["TenantID"] = o.TenantID
	}
	return toSerialize, nil
}

func (o *GetTenantHostResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"StatusCode",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetTenantHostResponse := _GetTenantHostResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetTenantHostResponse)

	if err != nil {
		return err
	}

	*o = GetTenantHostResponse(varGetTenantHostResponse)

	return err
}

type NullableGetTenantHostResponse struct {
	value *GetTenantHostResponse
	isSet bool
}

func (v NullableGetTenantHostResponse) Get() *GetTenantHostResponse {
	return v.value
}

func (v *NullableGetTenantHostResponse) Set(val *GetTenantHostResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetTenantHostResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetTenantHostResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetTenantHostResponse(val *GetTenantHostResponse) *NullableGetTenantHostResponse {
	return &NullableGetTenantHostResponse{value: val, isSet: true}
}

func (v NullableGetTenantHostResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetTenantHostResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
