/*
Volumez API

Volumez orchestrator API

API version: 1.0.0 - 8d1ee8c4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CapacityGroup type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CapacityGroup{}

// CapacityGroup struct for CapacityGroup
type CapacityGroup struct {
	Name *string `json:"name,omitempty"`
}

// NewCapacityGroup instantiates a new CapacityGroup object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCapacityGroup() *CapacityGroup {
	this := CapacityGroup{}
	return &this
}

// NewCapacityGroupWithDefaults instantiates a new CapacityGroup object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCapacityGroupWithDefaults() *CapacityGroup {
	this := CapacityGroup{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CapacityGroup) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapacityGroup) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CapacityGroup) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CapacityGroup) SetName(v string) {
	o.Name = &v
}

func (o CapacityGroup) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CapacityGroup) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableCapacityGroup struct {
	value *CapacityGroup
	isSet bool
}

func (v NullableCapacityGroup) Get() *CapacityGroup {
	return v.value
}

func (v *NullableCapacityGroup) Set(val *CapacityGroup) {
	v.value = val
	v.isSet = true
}

func (v NullableCapacityGroup) IsSet() bool {
	return v.isSet
}

func (v *NullableCapacityGroup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCapacityGroup(val *CapacityGroup) *NullableCapacityGroup {
	return &NullableCapacityGroup{value: val, isSet: true}
}

func (v NullableCapacityGroup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCapacityGroup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
