/*
Volumez API

Volumez orchestrator API

API version: 1.0.0 - 8d1ee8c4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SuccessJobResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SuccessJobResponse{}

// SuccessJobResponse struct for SuccessJobResponse
type SuccessJobResponse struct {
	Message  *string `json:"Message,omitempty"`
	JobID    *string `json:"JobID,omitempty"`
	ObjectID *string `json:"ObjectID,omitempty"`
}

// NewSuccessJobResponse instantiates a new SuccessJobResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSuccessJobResponse() *SuccessJobResponse {
	this := SuccessJobResponse{}
	return &this
}

// NewSuccessJobResponseWithDefaults instantiates a new SuccessJobResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSuccessJobResponseWithDefaults() *SuccessJobResponse {
	this := SuccessJobResponse{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *SuccessJobResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuccessJobResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *SuccessJobResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *SuccessJobResponse) SetMessage(v string) {
	o.Message = &v
}

// GetJobID returns the JobID field value if set, zero value otherwise.
func (o *SuccessJobResponse) GetJobID() string {
	if o == nil || IsNil(o.JobID) {
		var ret string
		return ret
	}
	return *o.JobID
}

// GetJobIDOk returns a tuple with the JobID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuccessJobResponse) GetJobIDOk() (*string, bool) {
	if o == nil || IsNil(o.JobID) {
		return nil, false
	}
	return o.JobID, true
}

// HasJobID returns a boolean if a field has been set.
func (o *SuccessJobResponse) HasJobID() bool {
	if o != nil && !IsNil(o.JobID) {
		return true
	}

	return false
}

// SetJobID gets a reference to the given string and assigns it to the JobID field.
func (o *SuccessJobResponse) SetJobID(v string) {
	o.JobID = &v
}

// GetObjectID returns the ObjectID field value if set, zero value otherwise.
func (o *SuccessJobResponse) GetObjectID() string {
	if o == nil || IsNil(o.ObjectID) {
		var ret string
		return ret
	}
	return *o.ObjectID
}

// GetObjectIDOk returns a tuple with the ObjectID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuccessJobResponse) GetObjectIDOk() (*string, bool) {
	if o == nil || IsNil(o.ObjectID) {
		return nil, false
	}
	return o.ObjectID, true
}

// HasObjectID returns a boolean if a field has been set.
func (o *SuccessJobResponse) HasObjectID() bool {
	if o != nil && !IsNil(o.ObjectID) {
		return true
	}

	return false
}

// SetObjectID gets a reference to the given string and assigns it to the ObjectID field.
func (o *SuccessJobResponse) SetObjectID(v string) {
	o.ObjectID = &v
}

func (o SuccessJobResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SuccessJobResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["Message"] = o.Message
	}
	if !IsNil(o.JobID) {
		toSerialize["JobID"] = o.JobID
	}
	if !IsNil(o.ObjectID) {
		toSerialize["ObjectID"] = o.ObjectID
	}
	return toSerialize, nil
}

type NullableSuccessJobResponse struct {
	value *SuccessJobResponse
	isSet bool
}

func (v NullableSuccessJobResponse) Get() *SuccessJobResponse {
	return v.value
}

func (v *NullableSuccessJobResponse) Set(val *SuccessJobResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSuccessJobResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSuccessJobResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSuccessJobResponse(val *SuccessJobResponse) *NullableSuccessJobResponse {
	return &NullableSuccessJobResponse{value: val, isSet: true}
}

func (v NullableSuccessJobResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSuccessJobResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
