// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CapacityGroup capacity group
//
// swagger:model CapacityGroup
type CapacityGroup struct {

	// name
	Name string `json:"name"`
}

// Validate validates this capacity group
func (m *CapacityGroup) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this capacity group based on context it is used
func (m *CapacityGroup) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CapacityGroup) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CapacityGroup) UnmarshalBinary(b []byte) error {
	var res CapacityGroup
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
