// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Plan plan
//
// swagger:model Plan
type Plan struct {

	// replicationvolumegroup
	Replicationvolumegroup *VolumeGroup `json:"replicationvolumegroup,omitempty"`

	// volumegroup
	Volumegroup *VolumeGroup `json:"volumegroup,omitempty"`
}

// Validate validates this plan
func (m *Plan) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateReplicationvolumegroup(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVolumegroup(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Plan) validateReplicationvolumegroup(formats strfmt.Registry) error {
	if swag.IsZero(m.Replicationvolumegroup) { // not required
		return nil
	}

	if m.Replicationvolumegroup != nil {
		if err := m.Replicationvolumegroup.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("replicationvolumegroup")
			}
			return err
		}
	}

	return nil
}

func (m *Plan) validateVolumegroup(formats strfmt.Registry) error {
	if swag.IsZero(m.Volumegroup) { // not required
		return nil
	}

	if m.Volumegroup != nil {
		if err := m.Volumegroup.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("volumegroup")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this plan based on the context it is used
func (m *Plan) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateReplicationvolumegroup(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateVolumegroup(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Plan) contextValidateReplicationvolumegroup(ctx context.Context, formats strfmt.Registry) error {

	if m.Replicationvolumegroup != nil {
		if err := m.Replicationvolumegroup.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("replicationvolumegroup")
			}
			return err
		}
	}

	return nil
}

func (m *Plan) contextValidateVolumegroup(ctx context.Context, formats strfmt.Registry) error {

	if m.Volumegroup != nil {
		if err := m.Volumegroup.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("volumegroup")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Plan) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Plan) UnmarshalBinary(b []byte) error {
	var res Plan
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
