// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RegularResponse regular response
//
// swagger:model RegularResponse
type RegularResponse struct {

	// message
	Message string `json:"Message"`
}

// Validate validates this regular response
func (m *RegularResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this regular response based on context it is used
func (m *RegularResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RegularResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RegularResponse) UnmarshalBinary(b []byte) error {
	var res RegularResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
