// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RequestChangePasswordRequest request change password request
//
// swagger:model RequestChangePasswordRequest
type RequestChangePasswordRequest struct {

	// email
	Email string `json:"email"`
}

// Validate validates this request change password request
func (m *RequestChangePasswordRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this request change password request based on context it is used
func (m *RequestChangePasswordRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RequestChangePasswordRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RequestChangePasswordRequest) UnmarshalBinary(b []byte) error {
	var res RequestChangePasswordRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
