// Code generated by go-swagger; DO NOT EDIT.

package connectivities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/VolumezTech/volumez-rest-client/restapi/models"
)

// ConnectivitiesListReader is a Reader for the ConnectivitiesList structure.
type ConnectivitiesListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ConnectivitiesListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewConnectivitiesListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewConnectivitiesListDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewConnectivitiesListOK creates a ConnectivitiesListOK with default headers values
func NewConnectivitiesListOK() *ConnectivitiesListOK {
	return &ConnectivitiesListOK{}
}

/*
ConnectivitiesListOK describes a response with status code 200, with default header values.

List of connectivities
*/
type ConnectivitiesListOK struct {
	Payload []*models.Connectivity
}

// IsSuccess returns true when this connectivities list o k response has a 2xx status code
func (o *ConnectivitiesListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this connectivities list o k response has a 3xx status code
func (o *ConnectivitiesListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this connectivities list o k response has a 4xx status code
func (o *ConnectivitiesListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this connectivities list o k response has a 5xx status code
func (o *ConnectivitiesListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this connectivities list o k response a status code equal to that given
func (o *ConnectivitiesListOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the connectivities list o k response
func (o *ConnectivitiesListOK) Code() int {
	return 200
}

func (o *ConnectivitiesListOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /connectivities][%d] connectivitiesListOK %s", 200, payload)
}

func (o *ConnectivitiesListOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /connectivities][%d] connectivitiesListOK %s", 200, payload)
}

func (o *ConnectivitiesListOK) GetPayload() []*models.Connectivity {
	return o.Payload
}

func (o *ConnectivitiesListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewConnectivitiesListDefault creates a ConnectivitiesListDefault with default headers values
func NewConnectivitiesListDefault(code int) *ConnectivitiesListDefault {
	return &ConnectivitiesListDefault{
		_statusCode: code,
	}
}

/*
ConnectivitiesListDefault describes a response with status code -1, with default header values.

Error getting a list of connectivities
*/
type ConnectivitiesListDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// IsSuccess returns true when this connectivities list default response has a 2xx status code
func (o *ConnectivitiesListDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this connectivities list default response has a 3xx status code
func (o *ConnectivitiesListDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this connectivities list default response has a 4xx status code
func (o *ConnectivitiesListDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this connectivities list default response has a 5xx status code
func (o *ConnectivitiesListDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this connectivities list default response a status code equal to that given
func (o *ConnectivitiesListDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the connectivities list default response
func (o *ConnectivitiesListDefault) Code() int {
	return o._statusCode
}

func (o *ConnectivitiesListDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /connectivities][%d] ConnectivitiesList default %s", o._statusCode, payload)
}

func (o *ConnectivitiesListDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /connectivities][%d] ConnectivitiesList default %s", o._statusCode, payload)
}

func (o *ConnectivitiesListDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ConnectivitiesListDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
