// Code generated by go-swagger; DO NOT EDIT.

package tenant_host

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/VolumezTech/volumez-rest-client/restapi/models"
)

// TenanthostgetReader is a Reader for the Tenanthostget structure.
type TenanthostgetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TenanthostgetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewTenanthostgetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewTenanthostgetInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewTenanthostgetOK creates a TenanthostgetOK with default headers values
func NewTenanthostgetOK() *TenanthostgetOK {
	return &TenanthostgetOK{}
}

/* TenanthostgetOK describes a response with status code 200, with default header values.

Got Tenant's Host successfully
*/
type TenanthostgetOK struct {
	Payload *models.GetTenantHostResponse
}

func (o *TenanthostgetOK) Error() string {
	return fmt.Sprintf("[GET /tenant/tenanthost][%d] tenanthostgetOK  %+v", 200, o.Payload)
}
func (o *TenanthostgetOK) GetPayload() *models.GetTenantHostResponse {
	return o.Payload
}

func (o *TenanthostgetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetTenantHostResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewTenanthostgetInternalServerError creates a TenanthostgetInternalServerError with default headers values
func NewTenanthostgetInternalServerError() *TenanthostgetInternalServerError {
	return &TenanthostgetInternalServerError{}
}

/* TenanthostgetInternalServerError describes a response with status code 500, with default header values.

Error getting Tenant's Host
*/
type TenanthostgetInternalServerError struct {
	Payload *models.GetTenantHostResponse
}

func (o *TenanthostgetInternalServerError) Error() string {
	return fmt.Sprintf("[GET /tenant/tenanthost][%d] tenanthostgetInternalServerError  %+v", 500, o.Payload)
}
func (o *TenanthostgetInternalServerError) GetPayload() *models.GetTenantHostResponse {
	return o.Payload
}

func (o *TenanthostgetInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetTenantHostResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
