// Code generated by go-swagger; DO NOT EDIT.

package networks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/VolumezTech/volumez-rest-client/restapi/models"
)

// NetworkDeleteReader is a Reader for the NetworkDelete structure.
type NetworkDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *NetworkDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewNetworkDeleteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewNetworkDeleteDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewNetworkDeleteOK creates a NetworkDeleteOK with default headers values
func NewNetworkDeleteOK() *NetworkDeleteOK {
	return &NetworkDeleteOK{}
}

/*
NetworkDeleteOK describes a response with status code 200, with default header values.

A network was deleted successfully
*/
type NetworkDeleteOK struct {
	Payload *models.RegularResponse
}

func (o *NetworkDeleteOK) Error() string {
	return fmt.Sprintf("[DELETE /networks/{network}][%d] networkDeleteOK  %+v", 200, o.Payload)
}
func (o *NetworkDeleteOK) GetPayload() *models.RegularResponse {
	return o.Payload
}

func (o *NetworkDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RegularResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewNetworkDeleteDefault creates a NetworkDeleteDefault with default headers values
func NewNetworkDeleteDefault(code int) *NetworkDeleteDefault {
	return &NetworkDeleteDefault{
		_statusCode: code,
	}
}

/*
NetworkDeleteDefault describes a response with status code -1, with default header values.

Error deleting a network
*/
type NetworkDeleteDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the network delete default response
func (o *NetworkDeleteDefault) Code() int {
	return o._statusCode
}

func (o *NetworkDeleteDefault) Error() string {
	return fmt.Sprintf("[DELETE /networks/{network}][%d] NetworkDelete default  %+v", o._statusCode, o.Payload)
}
func (o *NetworkDeleteDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *NetworkDeleteDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
