// Code generated by go-swagger; DO NOT EDIT.

package networks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/VolumezTech/volumez-rest-client/restapi/models"
)

// NetworkDeleteReader is a Reader for the NetworkDelete structure.
type NetworkDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *NetworkDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewNetworkDeleteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewNetworkDeleteDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewNetworkDeleteOK creates a NetworkDeleteOK with default headers values
func NewNetworkDeleteOK() *NetworkDeleteOK {
	return &NetworkDeleteOK{}
}

/*
NetworkDeleteOK describes a response with status code 200, with default header values.

A network was deleted successfully
*/
type NetworkDeleteOK struct {
	Payload *models.RegularResponse
}

// IsSuccess returns true when this network delete o k response has a 2xx status code
func (o *NetworkDeleteOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this network delete o k response has a 3xx status code
func (o *NetworkDeleteOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this network delete o k response has a 4xx status code
func (o *NetworkDeleteOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this network delete o k response has a 5xx status code
func (o *NetworkDeleteOK) IsServerError() bool {
	return false
}

// IsCode returns true when this network delete o k response a status code equal to that given
func (o *NetworkDeleteOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the network delete o k response
func (o *NetworkDeleteOK) Code() int {
	return 200
}

func (o *NetworkDeleteOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /networks/{network}][%d] networkDeleteOK %s", 200, payload)
}

func (o *NetworkDeleteOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /networks/{network}][%d] networkDeleteOK %s", 200, payload)
}

func (o *NetworkDeleteOK) GetPayload() *models.RegularResponse {
	return o.Payload
}

func (o *NetworkDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RegularResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewNetworkDeleteDefault creates a NetworkDeleteDefault with default headers values
func NewNetworkDeleteDefault(code int) *NetworkDeleteDefault {
	return &NetworkDeleteDefault{
		_statusCode: code,
	}
}

/*
NetworkDeleteDefault describes a response with status code -1, with default header values.

Error deleting a network
*/
type NetworkDeleteDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// IsSuccess returns true when this network delete default response has a 2xx status code
func (o *NetworkDeleteDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this network delete default response has a 3xx status code
func (o *NetworkDeleteDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this network delete default response has a 4xx status code
func (o *NetworkDeleteDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this network delete default response has a 5xx status code
func (o *NetworkDeleteDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this network delete default response a status code equal to that given
func (o *NetworkDeleteDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the network delete default response
func (o *NetworkDeleteDefault) Code() int {
	return o._statusCode
}

func (o *NetworkDeleteDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /networks/{network}][%d] NetworkDelete default %s", o._statusCode, payload)
}

func (o *NetworkDeleteDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /networks/{network}][%d] NetworkDelete default %s", o._statusCode, payload)
}

func (o *NetworkDeleteDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *NetworkDeleteDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
