// Code generated by go-swagger; DO NOT EDIT.

package media

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewMediaUnassignParams creates a new MediaUnassignParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewMediaUnassignParams() *MediaUnassignParams {
	return &MediaUnassignParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewMediaUnassignParamsWithTimeout creates a new MediaUnassignParams object
// with the ability to set a timeout on a request.
func NewMediaUnassignParamsWithTimeout(timeout time.Duration) *MediaUnassignParams {
	return &MediaUnassignParams{
		timeout: timeout,
	}
}

// NewMediaUnassignParamsWithContext creates a new MediaUnassignParams object
// with the ability to set a context for a request.
func NewMediaUnassignParamsWithContext(ctx context.Context) *MediaUnassignParams {
	return &MediaUnassignParams{
		Context: ctx,
	}
}

// NewMediaUnassignParamsWithHTTPClient creates a new MediaUnassignParams object
// with the ability to set a custom HTTPClient for a request.
func NewMediaUnassignParamsWithHTTPClient(client *http.Client) *MediaUnassignParams {
	return &MediaUnassignParams{
		HTTPClient: client,
	}
}

/* MediaUnassignParams contains all the parameters to send to the API endpoint
   for the media unassign operation.

   Typically these are written to a http.Request.
*/
type MediaUnassignParams struct {

	// Authorization.
	Authorization *string

	// Media.
	Media string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the media unassign params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MediaUnassignParams) WithDefaults() *MediaUnassignParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the media unassign params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MediaUnassignParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the media unassign params
func (o *MediaUnassignParams) WithTimeout(timeout time.Duration) *MediaUnassignParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the media unassign params
func (o *MediaUnassignParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the media unassign params
func (o *MediaUnassignParams) WithContext(ctx context.Context) *MediaUnassignParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the media unassign params
func (o *MediaUnassignParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the media unassign params
func (o *MediaUnassignParams) WithHTTPClient(client *http.Client) *MediaUnassignParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the media unassign params
func (o *MediaUnassignParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the media unassign params
func (o *MediaUnassignParams) WithAuthorization(authorization *string) *MediaUnassignParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the media unassign params
func (o *MediaUnassignParams) SetAuthorization(authorization *string) {
	o.Authorization = authorization
}

// WithMedia adds the media to the media unassign params
func (o *MediaUnassignParams) WithMedia(media string) *MediaUnassignParams {
	o.SetMedia(media)
	return o
}

// SetMedia adds the media to the media unassign params
func (o *MediaUnassignParams) SetMedia(media string) {
	o.Media = media
}

// WriteToRequest writes these params to a swagger request
func (o *MediaUnassignParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Authorization != nil {

		// header param authorization
		if err := r.SetHeaderParam("authorization", *o.Authorization); err != nil {
			return err
		}
	}

	// path param media
	if err := r.SetPathParam("media", o.Media); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
