// Code generated by go-swagger; DO NOT EDIT.

package media

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/VolumezTech/volumez-rest-client/restapi/models"
)

// MediaGetReader is a Reader for the MediaGet structure.
type MediaGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MediaGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewMediaGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewMediaGetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewMediaGetOK creates a MediaGetOK with default headers values
func NewMediaGetOK() *MediaGetOK {
	return &MediaGetOK{}
}

/*
MediaGetOK describes a response with status code 200, with default header values.

Properties of a media
*/
type MediaGetOK struct {
	Payload *models.Media
}

// IsSuccess returns true when this media get o k response has a 2xx status code
func (o *MediaGetOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this media get o k response has a 3xx status code
func (o *MediaGetOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this media get o k response has a 4xx status code
func (o *MediaGetOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this media get o k response has a 5xx status code
func (o *MediaGetOK) IsServerError() bool {
	return false
}

// IsCode returns true when this media get o k response a status code equal to that given
func (o *MediaGetOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the media get o k response
func (o *MediaGetOK) Code() int {
	return 200
}

func (o *MediaGetOK) Error() string {
	return fmt.Sprintf("[GET /media/{media}][%d] mediaGetOK  %+v", 200, o.Payload)
}

func (o *MediaGetOK) String() string {
	return fmt.Sprintf("[GET /media/{media}][%d] mediaGetOK  %+v", 200, o.Payload)
}

func (o *MediaGetOK) GetPayload() *models.Media {
	return o.Payload
}

func (o *MediaGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Media)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMediaGetDefault creates a MediaGetDefault with default headers values
func NewMediaGetDefault(code int) *MediaGetDefault {
	return &MediaGetDefault{
		_statusCode: code,
	}
}

/*
MediaGetDefault describes a response with status code -1, with default header values.

Error getting properties of a media
*/
type MediaGetDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// IsSuccess returns true when this media get default response has a 2xx status code
func (o *MediaGetDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this media get default response has a 3xx status code
func (o *MediaGetDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this media get default response has a 4xx status code
func (o *MediaGetDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this media get default response has a 5xx status code
func (o *MediaGetDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this media get default response a status code equal to that given
func (o *MediaGetDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the media get default response
func (o *MediaGetDefault) Code() int {
	return o._statusCode
}

func (o *MediaGetDefault) Error() string {
	return fmt.Sprintf("[GET /media/{media}][%d] MediaGet default  %+v", o._statusCode, o.Payload)
}

func (o *MediaGetDefault) String() string {
	return fmt.Sprintf("[GET /media/{media}][%d] MediaGet default  %+v", o._statusCode, o.Payload)
}

func (o *MediaGetDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *MediaGetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
