// Code generated by go-swagger; DO NOT EDIT.

package media

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/VolumezTech/volumez-rest-client/restapi/models"
)

// MediaCleanupVolumeReader is a Reader for the MediaCleanupVolume structure.
type MediaCleanupVolumeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MediaCleanupVolumeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewMediaCleanupVolumeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewMediaCleanupVolumeDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewMediaCleanupVolumeOK creates a MediaCleanupVolumeOK with default headers values
func NewMediaCleanupVolumeOK() *MediaCleanupVolumeOK {
	return &MediaCleanupVolumeOK{}
}

/* MediaCleanupVolumeOK describes a response with status code 200, with default header values.

Operation completed successfully
*/
type MediaCleanupVolumeOK struct {
	Payload *models.RegularResponse
}

func (o *MediaCleanupVolumeOK) Error() string {
	return fmt.Sprintf("[POST /media/{media}/cleanup/{volume}][%d] mediaCleanupVolumeOK  %+v", 200, o.Payload)
}
func (o *MediaCleanupVolumeOK) GetPayload() *models.RegularResponse {
	return o.Payload
}

func (o *MediaCleanupVolumeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RegularResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMediaCleanupVolumeDefault creates a MediaCleanupVolumeDefault with default headers values
func NewMediaCleanupVolumeDefault(code int) *MediaCleanupVolumeDefault {
	return &MediaCleanupVolumeDefault{
		_statusCode: code,
	}
}

/* MediaCleanupVolumeDefault describes a response with status code -1, with default header values.

Error cleaning media's volume
*/
type MediaCleanupVolumeDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the media cleanup volume default response
func (o *MediaCleanupVolumeDefault) Code() int {
	return o._statusCode
}

func (o *MediaCleanupVolumeDefault) Error() string {
	return fmt.Sprintf("[POST /media/{media}/cleanup/{volume}][%d] MediaCleanupVolume default  %+v", o._statusCode, o.Payload)
}
func (o *MediaCleanupVolumeDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *MediaCleanupVolumeDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
