// Code generated by go-swagger; DO NOT EDIT.

package media

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewVirtualMediaListParams creates a new VirtualMediaListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewVirtualMediaListParams() *VirtualMediaListParams {
	return &VirtualMediaListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewVirtualMediaListParamsWithTimeout creates a new VirtualMediaListParams object
// with the ability to set a timeout on a request.
func NewVirtualMediaListParamsWithTimeout(timeout time.Duration) *VirtualMediaListParams {
	return &VirtualMediaListParams{
		timeout: timeout,
	}
}

// NewVirtualMediaListParamsWithContext creates a new VirtualMediaListParams object
// with the ability to set a context for a request.
func NewVirtualMediaListParamsWithContext(ctx context.Context) *VirtualMediaListParams {
	return &VirtualMediaListParams{
		Context: ctx,
	}
}

// NewVirtualMediaListParamsWithHTTPClient creates a new VirtualMediaListParams object
// with the ability to set a custom HTTPClient for a request.
func NewVirtualMediaListParamsWithHTTPClient(client *http.Client) *VirtualMediaListParams {
	return &VirtualMediaListParams{
		HTTPClient: client,
	}
}

/*
VirtualMediaListParams contains all the parameters to send to the API endpoint

	for the virtual media list operation.

	Typically these are written to a http.Request.
*/
type VirtualMediaListParams struct {

	// Authorization.
	Authorization *string

	// Count.
	Count *int64

	// Startfrom.
	Startfrom *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the virtual media list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VirtualMediaListParams) WithDefaults() *VirtualMediaListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the virtual media list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VirtualMediaListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the virtual media list params
func (o *VirtualMediaListParams) WithTimeout(timeout time.Duration) *VirtualMediaListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the virtual media list params
func (o *VirtualMediaListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the virtual media list params
func (o *VirtualMediaListParams) WithContext(ctx context.Context) *VirtualMediaListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the virtual media list params
func (o *VirtualMediaListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the virtual media list params
func (o *VirtualMediaListParams) WithHTTPClient(client *http.Client) *VirtualMediaListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the virtual media list params
func (o *VirtualMediaListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the virtual media list params
func (o *VirtualMediaListParams) WithAuthorization(authorization *string) *VirtualMediaListParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the virtual media list params
func (o *VirtualMediaListParams) SetAuthorization(authorization *string) {
	o.Authorization = authorization
}

// WithCount adds the count to the virtual media list params
func (o *VirtualMediaListParams) WithCount(count *int64) *VirtualMediaListParams {
	o.SetCount(count)
	return o
}

// SetCount adds the count to the virtual media list params
func (o *VirtualMediaListParams) SetCount(count *int64) {
	o.Count = count
}

// WithStartfrom adds the startfrom to the virtual media list params
func (o *VirtualMediaListParams) WithStartfrom(startfrom *string) *VirtualMediaListParams {
	o.SetStartfrom(startfrom)
	return o
}

// SetStartfrom adds the startfrom to the virtual media list params
func (o *VirtualMediaListParams) SetStartfrom(startfrom *string) {
	o.Startfrom = startfrom
}

// WriteToRequest writes these params to a swagger request
func (o *VirtualMediaListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Authorization != nil {

		// header param authorization
		if err := r.SetHeaderParam("authorization", *o.Authorization); err != nil {
			return err
		}
	}

	if o.Count != nil {

		// query param count
		var qrCount int64

		if o.Count != nil {
			qrCount = *o.Count
		}
		qCount := swag.FormatInt64(qrCount)
		if qCount != "" {

			if err := r.SetQueryParam("count", qCount); err != nil {
				return err
			}
		}
	}

	if o.Startfrom != nil {

		// query param startfrom
		var qrStartfrom string

		if o.Startfrom != nil {
			qrStartfrom = *o.Startfrom
		}
		qStartfrom := qrStartfrom
		if qStartfrom != "" {

			if err := r.SetQueryParam("startfrom", qStartfrom); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
