// Code generated by go-swagger; DO NOT EDIT.

package media

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/VolumezTech/volumez-rest-client/restapi/models"
)

// NewVirtualMediaCreateParams creates a new VirtualMediaCreateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewVirtualMediaCreateParams() *VirtualMediaCreateParams {
	return &VirtualMediaCreateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewVirtualMediaCreateParamsWithTimeout creates a new VirtualMediaCreateParams object
// with the ability to set a timeout on a request.
func NewVirtualMediaCreateParamsWithTimeout(timeout time.Duration) *VirtualMediaCreateParams {
	return &VirtualMediaCreateParams{
		timeout: timeout,
	}
}

// NewVirtualMediaCreateParamsWithContext creates a new VirtualMediaCreateParams object
// with the ability to set a context for a request.
func NewVirtualMediaCreateParamsWithContext(ctx context.Context) *VirtualMediaCreateParams {
	return &VirtualMediaCreateParams{
		Context: ctx,
	}
}

// NewVirtualMediaCreateParamsWithHTTPClient creates a new VirtualMediaCreateParams object
// with the ability to set a custom HTTPClient for a request.
func NewVirtualMediaCreateParamsWithHTTPClient(client *http.Client) *VirtualMediaCreateParams {
	return &VirtualMediaCreateParams{
		HTTPClient: client,
	}
}

/*
VirtualMediaCreateParams contains all the parameters to send to the API endpoint

	for the virtual media create operation.

	Typically these are written to a http.Request.
*/
type VirtualMediaCreateParams struct {

	// Authorization.
	Authorization *string

	/* Body.

	   Virtual media creation parameters
	*/
	Body *models.VirtualMediaCreate

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the virtual media create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VirtualMediaCreateParams) WithDefaults() *VirtualMediaCreateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the virtual media create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VirtualMediaCreateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the virtual media create params
func (o *VirtualMediaCreateParams) WithTimeout(timeout time.Duration) *VirtualMediaCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the virtual media create params
func (o *VirtualMediaCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the virtual media create params
func (o *VirtualMediaCreateParams) WithContext(ctx context.Context) *VirtualMediaCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the virtual media create params
func (o *VirtualMediaCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the virtual media create params
func (o *VirtualMediaCreateParams) WithHTTPClient(client *http.Client) *VirtualMediaCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the virtual media create params
func (o *VirtualMediaCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the virtual media create params
func (o *VirtualMediaCreateParams) WithAuthorization(authorization *string) *VirtualMediaCreateParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the virtual media create params
func (o *VirtualMediaCreateParams) SetAuthorization(authorization *string) {
	o.Authorization = authorization
}

// WithBody adds the body to the virtual media create params
func (o *VirtualMediaCreateParams) WithBody(body *models.VirtualMediaCreate) *VirtualMediaCreateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the virtual media create params
func (o *VirtualMediaCreateParams) SetBody(body *models.VirtualMediaCreate) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *VirtualMediaCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Authorization != nil {

		// header param authorization
		if err := r.SetHeaderParam("authorization", *o.Authorization); err != nil {
			return err
		}
	}
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
