// Code generated by go-swagger; DO NOT EDIT.

package media

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/VolumezTech/volumez-rest-client/restapi/models"
)

// VirtualMediaCreateReader is a Reader for the VirtualMediaCreate structure.
type VirtualMediaCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *VirtualMediaCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewVirtualMediaCreateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewVirtualMediaCreateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewVirtualMediaCreateOK creates a VirtualMediaCreateOK with default headers values
func NewVirtualMediaCreateOK() *VirtualMediaCreateOK {
	return &VirtualMediaCreateOK{}
}

/*
	VirtualMediaCreateOK describes a response with status code 200, with default header values.

Virtual media has been created successfully
*/
type VirtualMediaCreateOK struct {
	Payload *models.SuccessJobResponse
}

func (o *VirtualMediaCreateOK) Error() string {
	return fmt.Sprintf("[POST /virtualmedia][%d] virtualMediaCreateOK  %+v", 200, o.Payload)
}
func (o *VirtualMediaCreateOK) GetPayload() *models.SuccessJobResponse {
	return o.Payload
}

func (o *VirtualMediaCreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SuccessJobResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewVirtualMediaCreateDefault creates a VirtualMediaCreateDefault with default headers values
func NewVirtualMediaCreateDefault(code int) *VirtualMediaCreateDefault {
	return &VirtualMediaCreateDefault{
		_statusCode: code,
	}
}

/*
	VirtualMediaCreateDefault describes a response with status code -1, with default header values.

Error creating virtual media
*/
type VirtualMediaCreateDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the virtual media create default response
func (o *VirtualMediaCreateDefault) Code() int {
	return o._statusCode
}

func (o *VirtualMediaCreateDefault) Error() string {
	return fmt.Sprintf("[POST /virtualmedia][%d] VirtualMediaCreate default  %+v", o._statusCode, o.Payload)
}
func (o *VirtualMediaCreateDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *VirtualMediaCreateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
