// Code generated by go-swagger; DO NOT EDIT.

package tenant_user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/VolumezTech/volumez-rest-client/restapi/models"
)

// TenantusergetReader is a Reader for the Tenantuserget structure.
type TenantusergetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TenantusergetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewTenantusergetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewTenantusergetInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewTenantusergetOK creates a TenantusergetOK with default headers values
func NewTenantusergetOK() *TenantusergetOK {
	return &TenantusergetOK{}
}

/* TenantusergetOK describes a response with status code 200, with default header values.

Got Tenant's User successfully
*/
type TenantusergetOK struct {
	Payload *models.GetTenanUserResponse
}

func (o *TenantusergetOK) Error() string {
	return fmt.Sprintf("[GET /tenant/user][%d] tenantusergetOK  %+v", 200, o.Payload)
}
func (o *TenantusergetOK) GetPayload() *models.GetTenanUserResponse {
	return o.Payload
}

func (o *TenantusergetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetTenanUserResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewTenantusergetInternalServerError creates a TenantusergetInternalServerError with default headers values
func NewTenantusergetInternalServerError() *TenantusergetInternalServerError {
	return &TenantusergetInternalServerError{}
}

/* TenantusergetInternalServerError describes a response with status code 500, with default header values.

Error getting Tenant's User
*/
type TenantusergetInternalServerError struct {
	Payload *models.GetTenanUserResponse
}

func (o *TenantusergetInternalServerError) Error() string {
	return fmt.Sprintf("[GET /tenant/user][%d] tenantusergetInternalServerError  %+v", 500, o.Payload)
}
func (o *TenantusergetInternalServerError) GetPayload() *models.GetTenanUserResponse {
	return o.Payload
}

func (o *TenantusergetInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetTenanUserResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
