// Code generated by go-swagger; DO NOT EDIT.

package attachments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/VolumezTech/volumez-rest-client/restapi/models"
)

// AttachmentsListForVolumeReader is a Reader for the AttachmentsListForVolume structure.
type AttachmentsListForVolumeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AttachmentsListForVolumeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAttachmentsListForVolumeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewAttachmentsListForVolumeDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewAttachmentsListForVolumeOK creates a AttachmentsListForVolumeOK with default headers values
func NewAttachmentsListForVolumeOK() *AttachmentsListForVolumeOK {
	return &AttachmentsListForVolumeOK{}
}

/*
	AttachmentsListForVolumeOK describes a response with status code 200, with default header values.

List of attachments
*/
type AttachmentsListForVolumeOK struct {
	Payload []*models.Attachment
}

func (o *AttachmentsListForVolumeOK) Error() string {
	return fmt.Sprintf("[GET /volumes/{volume}/attachments][%d] attachmentsListForVolumeOK  %+v", 200, o.Payload)
}
func (o *AttachmentsListForVolumeOK) GetPayload() []*models.Attachment {
	return o.Payload
}

func (o *AttachmentsListForVolumeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAttachmentsListForVolumeDefault creates a AttachmentsListForVolumeDefault with default headers values
func NewAttachmentsListForVolumeDefault(code int) *AttachmentsListForVolumeDefault {
	return &AttachmentsListForVolumeDefault{
		_statusCode: code,
	}
}

/*
	AttachmentsListForVolumeDefault describes a response with status code -1, with default header values.

Error getting a list of attachments
*/
type AttachmentsListForVolumeDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the attachments list for volume default response
func (o *AttachmentsListForVolumeDefault) Code() int {
	return o._statusCode
}

func (o *AttachmentsListForVolumeDefault) Error() string {
	return fmt.Sprintf("[GET /volumes/{volume}/attachments][%d] AttachmentsListForVolume default  %+v", o._statusCode, o.Payload)
}
func (o *AttachmentsListForVolumeDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *AttachmentsListForVolumeDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
