// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/VolumezTech/volumez-rest-client/restapi/models"
)

// NewSignoutParams creates a new SignoutParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSignoutParams() *SignoutParams {
	return &SignoutParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSignoutParamsWithTimeout creates a new SignoutParams object
// with the ability to set a timeout on a request.
func NewSignoutParamsWithTimeout(timeout time.Duration) *SignoutParams {
	return &SignoutParams{
		timeout: timeout,
	}
}

// NewSignoutParamsWithContext creates a new SignoutParams object
// with the ability to set a context for a request.
func NewSignoutParamsWithContext(ctx context.Context) *SignoutParams {
	return &SignoutParams{
		Context: ctx,
	}
}

// NewSignoutParamsWithHTTPClient creates a new SignoutParams object
// with the ability to set a custom HTTPClient for a request.
func NewSignoutParamsWithHTTPClient(client *http.Client) *SignoutParams {
	return &SignoutParams{
		HTTPClient: client,
	}
}

/* SignoutParams contains all the parameters to send to the API endpoint
   for the signout operation.

   Typically these are written to a http.Request.
*/
type SignoutParams struct {

	/* Body.

	   Access Token
	*/
	Body *models.SignoutRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the signout params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SignoutParams) WithDefaults() *SignoutParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the signout params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SignoutParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the signout params
func (o *SignoutParams) WithTimeout(timeout time.Duration) *SignoutParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the signout params
func (o *SignoutParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the signout params
func (o *SignoutParams) WithContext(ctx context.Context) *SignoutParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the signout params
func (o *SignoutParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the signout params
func (o *SignoutParams) WithHTTPClient(client *http.Client) *SignoutParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the signout params
func (o *SignoutParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the signout params
func (o *SignoutParams) WithBody(body *models.SignoutRequest) *SignoutParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the signout params
func (o *SignoutParams) SetBody(body *models.SignoutRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *SignoutParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
