// Code generated by go-swagger; DO NOT EDIT.

package snapshots

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSnapshotsListParams creates a new SnapshotsListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSnapshotsListParams() *SnapshotsListParams {
	return &SnapshotsListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSnapshotsListParamsWithTimeout creates a new SnapshotsListParams object
// with the ability to set a timeout on a request.
func NewSnapshotsListParamsWithTimeout(timeout time.Duration) *SnapshotsListParams {
	return &SnapshotsListParams{
		timeout: timeout,
	}
}

// NewSnapshotsListParamsWithContext creates a new SnapshotsListParams object
// with the ability to set a context for a request.
func NewSnapshotsListParamsWithContext(ctx context.Context) *SnapshotsListParams {
	return &SnapshotsListParams{
		Context: ctx,
	}
}

// NewSnapshotsListParamsWithHTTPClient creates a new SnapshotsListParams object
// with the ability to set a custom HTTPClient for a request.
func NewSnapshotsListParamsWithHTTPClient(client *http.Client) *SnapshotsListParams {
	return &SnapshotsListParams{
		HTTPClient: client,
	}
}

/* SnapshotsListParams contains all the parameters to send to the API endpoint
   for the snapshots list operation.

   Typically these are written to a http.Request.
*/
type SnapshotsListParams struct {

	// Authorization.
	Authorization *string

	// Volume.
	Volume string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the snapshots list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SnapshotsListParams) WithDefaults() *SnapshotsListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the snapshots list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SnapshotsListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the snapshots list params
func (o *SnapshotsListParams) WithTimeout(timeout time.Duration) *SnapshotsListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the snapshots list params
func (o *SnapshotsListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the snapshots list params
func (o *SnapshotsListParams) WithContext(ctx context.Context) *SnapshotsListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the snapshots list params
func (o *SnapshotsListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the snapshots list params
func (o *SnapshotsListParams) WithHTTPClient(client *http.Client) *SnapshotsListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the snapshots list params
func (o *SnapshotsListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the snapshots list params
func (o *SnapshotsListParams) WithAuthorization(authorization *string) *SnapshotsListParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the snapshots list params
func (o *SnapshotsListParams) SetAuthorization(authorization *string) {
	o.Authorization = authorization
}

// WithVolume adds the volume to the snapshots list params
func (o *SnapshotsListParams) WithVolume(volume string) *SnapshotsListParams {
	o.SetVolume(volume)
	return o
}

// SetVolume adds the volume to the snapshots list params
func (o *SnapshotsListParams) SetVolume(volume string) {
	o.Volume = volume
}

// WriteToRequest writes these params to a swagger request
func (o *SnapshotsListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Authorization != nil {

		// header param authorization
		if err := r.SetHeaderParam("authorization", *o.Authorization); err != nil {
			return err
		}
	}

	// path param volume
	if err := r.SetPathParam("volume", o.Volume); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
