// Code generated by go-swagger; DO NOT EDIT.

package snapshots

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/VolumezTech/volumez-rest-client/restapi/models"
)

// SnapshotRollbackReader is a Reader for the SnapshotRollback structure.
type SnapshotRollbackReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SnapshotRollbackReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSnapshotRollbackOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewSnapshotRollbackDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewSnapshotRollbackOK creates a SnapshotRollbackOK with default headers values
func NewSnapshotRollbackOK() *SnapshotRollbackOK {
	return &SnapshotRollbackOK{}
}

/*
	SnapshotRollbackOK describes a response with status code 200, with default header values.

Rollback successful
*/
type SnapshotRollbackOK struct {
	Payload *models.RegularResponse
}

func (o *SnapshotRollbackOK) Error() string {
	return fmt.Sprintf("[PATCH /volumes/{volume}/snapshots/{snapshot}/rollback][%d] snapshotRollbackOK  %+v", 200, o.Payload)
}
func (o *SnapshotRollbackOK) GetPayload() *models.RegularResponse {
	return o.Payload
}

func (o *SnapshotRollbackOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RegularResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSnapshotRollbackDefault creates a SnapshotRollbackDefault with default headers values
func NewSnapshotRollbackDefault(code int) *SnapshotRollbackDefault {
	return &SnapshotRollbackDefault{
		_statusCode: code,
	}
}

/*
	SnapshotRollbackDefault describes a response with status code -1, with default header values.

Error during rollback
*/
type SnapshotRollbackDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the snapshot rollback default response
func (o *SnapshotRollbackDefault) Code() int {
	return o._statusCode
}

func (o *SnapshotRollbackDefault) Error() string {
	return fmt.Sprintf("[PATCH /volumes/{volume}/snapshots/{snapshot}/rollback][%d] SnapshotRollback default  %+v", o._statusCode, o.Payload)
}
func (o *SnapshotRollbackDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *SnapshotRollbackDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
