// Code generated by go-swagger; DO NOT EDIT.

package snapshots

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/VolumezTech/volumez-rest-client/restapi/models"
)

// NewSnapshotCreateParams creates a new SnapshotCreateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSnapshotCreateParams() *SnapshotCreateParams {
	return &SnapshotCreateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSnapshotCreateParamsWithTimeout creates a new SnapshotCreateParams object
// with the ability to set a timeout on a request.
func NewSnapshotCreateParamsWithTimeout(timeout time.Duration) *SnapshotCreateParams {
	return &SnapshotCreateParams{
		timeout: timeout,
	}
}

// NewSnapshotCreateParamsWithContext creates a new SnapshotCreateParams object
// with the ability to set a context for a request.
func NewSnapshotCreateParamsWithContext(ctx context.Context) *SnapshotCreateParams {
	return &SnapshotCreateParams{
		Context: ctx,
	}
}

// NewSnapshotCreateParamsWithHTTPClient creates a new SnapshotCreateParams object
// with the ability to set a custom HTTPClient for a request.
func NewSnapshotCreateParamsWithHTTPClient(client *http.Client) *SnapshotCreateParams {
	return &SnapshotCreateParams{
		HTTPClient: client,
	}
}

/*
SnapshotCreateParams contains all the parameters to send to the API endpoint

	for the snapshot create operation.

	Typically these are written to a http.Request.
*/
type SnapshotCreateParams struct {

	// Authorization.
	Authorization *string

	/* Body.

	   A Snapshot object
	*/
	Body *models.Snapshot

	// Volume.
	Volume string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the snapshot create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SnapshotCreateParams) WithDefaults() *SnapshotCreateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the snapshot create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SnapshotCreateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the snapshot create params
func (o *SnapshotCreateParams) WithTimeout(timeout time.Duration) *SnapshotCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the snapshot create params
func (o *SnapshotCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the snapshot create params
func (o *SnapshotCreateParams) WithContext(ctx context.Context) *SnapshotCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the snapshot create params
func (o *SnapshotCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the snapshot create params
func (o *SnapshotCreateParams) WithHTTPClient(client *http.Client) *SnapshotCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the snapshot create params
func (o *SnapshotCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the snapshot create params
func (o *SnapshotCreateParams) WithAuthorization(authorization *string) *SnapshotCreateParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the snapshot create params
func (o *SnapshotCreateParams) SetAuthorization(authorization *string) {
	o.Authorization = authorization
}

// WithBody adds the body to the snapshot create params
func (o *SnapshotCreateParams) WithBody(body *models.Snapshot) *SnapshotCreateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the snapshot create params
func (o *SnapshotCreateParams) SetBody(body *models.Snapshot) {
	o.Body = body
}

// WithVolume adds the volume to the snapshot create params
func (o *SnapshotCreateParams) WithVolume(volume string) *SnapshotCreateParams {
	o.SetVolume(volume)
	return o
}

// SetVolume adds the volume to the snapshot create params
func (o *SnapshotCreateParams) SetVolume(volume string) {
	o.Volume = volume
}

// WriteToRequest writes these params to a swagger request
func (o *SnapshotCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Authorization != nil {

		// header param authorization
		if err := r.SetHeaderParam("authorization", *o.Authorization); err != nil {
			return err
		}
	}
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param volume
	if err := r.SetPathParam("volume", o.Volume); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
