// Code generated by go-swagger; DO NOT EDIT.

package associations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new associations API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for associations API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	AssociationCreate(params *AssociationCreateParams, opts ...ClientOption) (*AssociationCreateOK, error)

	AssociationDelete(params *AssociationDeleteParams, opts ...ClientOption) (*AssociationDeleteOK, error)

	AssociationModify(params *AssociationModifyParams, opts ...ClientOption) (*AssociationModifyOK, error)

	AssociationsList(params *AssociationsListParams, opts ...ClientOption) (*AssociationsListOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  AssociationCreate creates association
*/
func (a *Client) AssociationCreate(params *AssociationCreateParams, opts ...ClientOption) (*AssociationCreateOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewAssociationCreateParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "AssociationCreate",
		Method:             "POST",
		PathPattern:        "/associations",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &AssociationCreateReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*AssociationCreateOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*AssociationCreateDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  AssociationDelete deletes an association
*/
func (a *Client) AssociationDelete(params *AssociationDeleteParams, opts ...ClientOption) (*AssociationDeleteOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewAssociationDeleteParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "AssociationDelete",
		Method:             "DELETE",
		PathPattern:        "/associations/{association}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &AssociationDeleteReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*AssociationDeleteOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*AssociationDeleteDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  AssociationModify associations modify
*/
func (a *Client) AssociationModify(params *AssociationModifyParams, opts ...ClientOption) (*AssociationModifyOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewAssociationModifyParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "AssociationModify",
		Method:             "PATCH",
		PathPattern:        "/associations/{association}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &AssociationModifyReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*AssociationModifyOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*AssociationModifyDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  AssociationsList gets a list of associations
*/
func (a *Client) AssociationsList(params *AssociationsListParams, opts ...ClientOption) (*AssociationsListOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewAssociationsListParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "AssociationsList",
		Method:             "GET",
		PathPattern:        "/associations",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &AssociationsListReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*AssociationsListOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*AssociationsListDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
