// Code generated by go-swagger; DO NOT EDIT.

package alerts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/VolumezTech/volumez-rest-client/restapi/models"
)

// AlertAcknowledgeReader is a Reader for the AlertAcknowledge structure.
type AlertAcknowledgeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AlertAcknowledgeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAlertAcknowledgeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewAlertAcknowledgeDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewAlertAcknowledgeOK creates a AlertAcknowledgeOK with default headers values
func NewAlertAcknowledgeOK() *AlertAcknowledgeOK {
	return &AlertAcknowledgeOK{}
}

/* AlertAcknowledgeOK describes a response with status code 200, with default header values.

Alert was successfully acknowledged
*/
type AlertAcknowledgeOK struct {
	Payload *models.RegularResponse
}

func (o *AlertAcknowledgeOK) Error() string {
	return fmt.Sprintf("[POST /alerts/{alert}/acknowledge][%d] alertAcknowledgeOK  %+v", 200, o.Payload)
}
func (o *AlertAcknowledgeOK) GetPayload() *models.RegularResponse {
	return o.Payload
}

func (o *AlertAcknowledgeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RegularResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAlertAcknowledgeDefault creates a AlertAcknowledgeDefault with default headers values
func NewAlertAcknowledgeDefault(code int) *AlertAcknowledgeDefault {
	return &AlertAcknowledgeDefault{
		_statusCode: code,
	}
}

/* AlertAcknowledgeDefault describes a response with status code -1, with default header values.

Error acknowledging alert
*/
type AlertAcknowledgeDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the alert acknowledge default response
func (o *AlertAcknowledgeDefault) Code() int {
	return o._statusCode
}

func (o *AlertAcknowledgeDefault) Error() string {
	return fmt.Sprintf("[POST /alerts/{alert}/acknowledge][%d] AlertAcknowledge default  %+v", o._statusCode, o.Payload)
}
func (o *AlertAcknowledgeDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *AlertAcknowledgeDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
